services:

  nitro-service:
    depends_on:
      cosmos:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NITRO_SEED_DATABASE=true
      - NITRO_COSMOS_ENDPOINT=http://localhost:8081
      - NITRO_COSMOS_KEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - NITRO_PORT=3030
    network_mode: host

  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports:
      - "8081:8081"
      - "1234:1234"
    environment:
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=0.0.0.0
    volumes:
      - cosmosdb:/usr/cosmos/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  cosmosdb:
